Toques finais Co-authored-by: MrSeguro <MrSeguro@users.noreply.github.com> Co-authored-by: Dinis Garcia <Sagan36@users.noreply.github.com>

diff --git a/pword b/pword
--- a/pword
+++ b/pword
@@ -1,27 +1,49 @@
-!/bin/bash
+#!/bin/bash
 PYTHON="python3" # Pode-se modificar esta variavel, se necessario
 PROGRAM="pword.py" # Nao pode modificar esta variavel
 #TO-DO: Validar o número de argumentos antes de chamar o Python (Ver TP02)
 #TO-DO: Validar que o ficheiro $PROGRAM existe antes de chama-lo (Ver TP02)
 
 file_true=false
+file_counter=0
+word_true=false
+process_true=false
+process_number=1
 
 if [ ! -f "$PROGRAM" ]; then
-    echo "Erro: This program does not exist"
+    echo "Error: This program does not exist"
+    exit 1
 else
     # Check if any arguments were provided
     if [ $# -eq 0 ]; then
         echo "You need to provide arguments."
-    else
-        for arg in "$@";do
+        exit 1
+    else # Check if the right arguments were provided
+        args=("$@")
+        length=${#args[@]}
+        for ((i=0; i<length; i++)); do
+            arg="${args[i]}"
             if [ -f "$arg" ] && [[ "$arg" == *.txt ]]; then
-                file_true=true  
-            fi
+                file_true=true 
+                ((file_count++))
+            elif [ "$arg" == -w ];then
+                word_true=true
+            elif [ "$arg" == -p ];then
+                process_true=true
+                process_number="${args[i+1]}"
+            fi  
         done
-        if [ "$file_true" = false ]; then
-            echo "One of the arguments you give must be a .txt file."
+        if [ "$file_true" = false ] || [ "$word_true" = false ] ; then
+            echo "The arguments must include a "-w word" argument and a .txt argument."
+            exit 1
         fi
     fi
-fi  
+fi
 
+#Checks if the number of processes is greater or equal of the number of files
+if [ "$process_number" -lt "$file_count" ];then
+    echo "The number of processes needs to be less or equal the amount of files you give."
+    exit 1
+fi    
 ${PYTHON} ${PROGRAM} $@
+exit 0
